# Generated by Django 5.1.15 on 2026-10-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_trending',
        ),
    ]
