# Generated by Django 5.1.15 on 2026-10-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_brand_is_featured_remove_category_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.productimage'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
