services:
  db:
    image: postgres:16-alpine
    container_name: wayaz_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wayaz
      POSTGRES_USER: wayaz
      POSTGRES_PASSWORD: wayaz_secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
